Document: myappdebian
Title: Debian myappdebian Manual
Author: <insert document author here>
Abstract: This manual describes what myappdebian is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/myappdebian/myappdebian.sgml.gz

Format: postscript
Files: /usr/share/doc/myappdebian/myappdebian.ps.gz

Format: text
Files: /usr/share/doc/myappdebian/myappdebian.text.gz

Format: HTML
Index: /usr/share/doc/myappdebian/html/index.html
Files: /usr/share/doc/myappdebian/html/*.html
