Document: debtest
Title: Debian debtest Manual
Author: <insert document author here>
Abstract: This manual describes what debtest is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/debtest/debtest.sgml.gz

Format: postscript
Files: /usr/share/doc/debtest/debtest.ps.gz

Format: text
Files: /usr/share/doc/debtest/debtest.text.gz

Format: HTML
Index: /usr/share/doc/debtest/html/index.html
Files: /usr/share/doc/debtest/html/*.html
